### ISSUE TITLE
META: blaggacao sunday sprint

### ISSUE THREAD

**Issue by blaggacao** [OCA/edi#130]
This is a meta issue to keep track of the current raid. All referenced issues are still WIP

**Comment by blaggacao** [comment]
#124 #125 #126 #127 #128 #129 #130 #131 #132 #134 #135 #136 #137

**Comment by blaggacao** [comment]
@pedrobaeza This is to make you happy again :wink: 
- [ ] Evaluate Issues worth of addressing by code
  - [ ] Bugs
  - [ ] Conditio sine qua non for broader use case
  - [ ] nice to have, future benefits
- [ ] Close otherwise (myself)
- [ ] Propose concrete implementations (PRs)
