### ISSUE TITLE
Migration to version 16.0

### ISSUE THREAD

**Issue by sbidoul** [OCA/edi#670]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0

# Modules to migrate

- [ ] account_einvoice_generate
- [x] account_invoice_export - By @TDu - #890
- [ ] account_invoice_facturx
- [x] base_business_document_import - By @gbrito-erpopen - #724
- [x] base_ebill_payment_contract - By @TDu - #889
- [ ] base_edi
- [x] base_edifact - By @QuocDuong1306 - #813
- [ ] base_facturx
- [x] base_ubl_payment - By @jbaudoux - #893
- [ ] edi_account_oca
- [ ] edi_backend_partner_oca TO MOVE to https://github.com/OCA/edi-framework
- [ ] edi_exchange_template_oca TO MOVE to https://github.com/OCA/edi-framework
- [ ] edi_oca MOVED TO https://github.com/OCA/edi-framework/pull/1
- [ ] edi_storage_oca TO MOVE to https://github.com/OCA/edi-framework
- [ ] edi_webservice_oca TO MOVE to https://github.com/OCA/edi-framework
- [ ] edi_backend_partner_oca TO MOVE to https://github.com/OCA/edi-framework
- [ ] pdf_helper - By @gbrito-erpopen - #723
- [x] sale_order_import - By @QuocDuong1306 - #816

Missing module? Check https://github.com/OCA/maintainer-tools/wiki/%5BFAQ%5D-Missing-modules-in-migration-issue-list

**Comment by john-herholz-dt** [comment]
base_edi #711

**Comment by hailangvn** [comment]
* account_invoice_import: WIP
(Please add to the list of modules above.)

**Comment by john-herholz-dt** [comment]
@simahawk , @sbidoul as I started migrating the EDI modules:
Does it make sense to merge base_edi and edi_oca?
Furthermore I saw a different menu icon in edi_oca then in base_edi. The one in edi_oca looks much better, can we use this for base_edi as well, then I will update my PR.

**Comment by alexis-via** [comment]
My roadmap for the migration of account_invoice_import to v16:
1) switch from single-file wizard to multi-file wizard
2) allow to share account.invoice.import.config across companies (company_id required=False and account_id field become company_dependent=True) ?
I you have some remarks/suggestions about these 2 changes, it's the good time to talk about it.

With @legalsylvain we also started to brainstorm about a re-write of the "update" scenario, but it will probably take time and arrive after the migration to v16.

**Comment by john-herholz-dt** [comment]
@sbidoul base_edi was merged,
I am currently doing edi_oca but it hangs on the tests. See PR #729

**Comment by Cedric-Pigeon** [comment]
@alexis-via What's the status of account_invoice_import migration ?
We'll need it in a really short-term. May be we can help you ?
Thanks,

**Comment by john-herholz-dt** [comment]
edi_backend_partner_oca is PR #745 
Waiting for dependency on PR #729 (Tests don't finish, I don't know the reason).
Can someone help?

**Comment by simahawk** [comment]
> @simahawk , @sbidoul as I started migrating the EDI modules: Does it make sense to merge base_edi and edi_oca? Furthermore I saw a different menu icon in edi_oca then in base_edi. The one in edi_oca looks much better, can we use this for base_edi as well, then I will update my PR.

Sorry for the late reply.
About merging module: no. It has been done like that to have a common entry point for EDI conf, no matter if you use the framework or not.
Regarding the icon: yeah, makes sense :+1:

**Comment by gomezgleonardob** [comment]
Hello ,It is considered to migrate this modules to v16?

https://github.com/OCA/edi/tree/14.0/account_invoice_import
https://github.com/OCA/edi/tree/14.0/account_invoice_import_facturx
https://github.com/OCA/edi/tree/14.0/account_invoice_import_ubl

And Same Variants

https://github.com/OCA/edi/tree/14.0/account_invoice_import_simple_pdf
https://github.com/OCA/edi/tree/14.0/account_invoice_import_invoice2data

**Comment by alexis-via** [comment]
@gomezgleonardob Most of these modules are already migrated to v16, just have a look at the pull requests.

**Comment by gomezgleonardob** [comment]
Thanks, I look the PR :D

**Comment by trisdoan** [comment]
working on `sale_order_packaging_import`
(Please add to the list of modules above.)
